import md5

from django.conf import settings

def compute_payment_request_mac(order):
    mac = md5.new()
    mac.update(settings.CHECKOUT_PARAMS['VERSION'])
    mac.update("+")
    mac.update(str(order.checkout_stamp))
    mac.update("+")
    mac.update(str(order.price_cents))
    mac.update("+")
    mac.update(order.reference_number)
    mac.update("+")
    mac.update(order.checkout_message)
    mac.update("+")
    mac.update(settings.CHECKOUT_PARAMS['LANGUAGE'])
    mac.update("+")
    mac.update(settings.CHECKOUT_PARAMS['MERCHANT'])
    mac.update("+")
    mac.update(settings.CHECKOUT_PARAMS['RETURN'])
    mac.update("+")
    mac.update("")
    mac.update("+")
    mac.update("")
    mac.update("+")
    mac.update("")
    mac.update("+")
    mac.update(settings.CHECKOUT_PARAMS['COUNTRY'])
    mac.update("+")
    mac.update(settings.CHECKOUT_PARAMS['CURRENCY'])
    mac.update("+")
    mac.update(settings.CHECKOUT_PARAMS['DEVICE'])
    mac.update("+")
    mac.update(settings.CHECKOUT_PARAMS['CONTENT'])
    mac.update("+")
    mac.update(settings.CHECKOUT_PARAMS['TYPE'])
    mac.update("+")
    mac.update(settings.CHECKOUT_PARAMS['ALGORITHM'])
    mac.update("+")
    mac.update(settings.CHECKOUT_PARAMS['DELIVERY_DATE'])
    mac.update("+")
    mac.update(order.customer.first_name)
    mac.update("+")
    mac.update(order.customer.last_name)
    mac.update("+")
    mac.update(order.customer.address)
    mac.update("+")
    mac.update(order.customer.zip_code)
    mac.update("+")
    mac.update(order.customer.city)
    mac.update("+")
    mac.update(settings.CHECKOUT_PARAMS['PASSWORD'])

    return mac.hexdigest().upper()
